Remove `bindgen` as build dependency for `adlx` (#8)
* Make binding generation an optinal feature

Use --features=bindgen

* Introduce api-gen crate

* Remove placeholder code from api-gen/lib.rs

* Add ADLX as submodule

* Remove checked in SDK files

* Fix wrapper.h

* Move ADLX to vendor/

* Submodule, api_gen rework (#9)

* Submodule, api_gen rework

* Renormalize line endings before `git diff`

* ci: Work around `regex` compilation failure in MSRV check

* Cleanup

* Fix clippy error

* Revert crate name back to adlx

* Fix error in example

---------

Co-authored-by: Marijn Suijten <marijn@traverseresearch.nl>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,5 +28,27 @@ jobs:
       - name: Generate minimal-version dependencies
         run: cargo -Zminimal-versions generate-lockfile
       - uses: dtolnay/rust-toolchain@1.74.0
+      - name: Upgrade to regex@1.5.1
+        # Workaround for:
+        # https://github.com/rust-lang/regex/issues/931
+        # https://github.com/rust-lang/rust-bindgen/pull/2714
+        run: cargo update -p regex --precise 1.5.1
       - name: Cargo check
         run: cargo check --workspace --all-targets
+
+  generate:
+    runs-on: windows-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Checkout submodule
+        # Manually update submodules with --checkout because they are configured with update=none and will be skipped otherwise
+        run: git submodule update --recursive --init --force --checkout
+      - name: Run generator
+        run: cargo r -p api_gen
+      - name: Normalize line endings
+        run: |
+          git add --renormalize -u
+          git reset
+      - name: Diff autogen result
+        shell: bash
+        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with cargo run -p api_gen!"; git diff; false)
